/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://okwy3nbcfveylgxmottykwyme4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-77pdqrexzrdchocu3zuw3osabq",
    "aws_cognito_identity_pool_id": "us-east-2:5b46ebab-c28d-46ab-8873-9028c418a8fe",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_hVjjkaqDQ",
    "aws_user_pools_web_client_id": "4ic7guf16h49ib3d7mmnuctba5",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "productstorage210431-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
