/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://fgwxdhyb3rg3hhibxha6yt44ye.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-uakpmre5zvatfh6tnot4b4j4ka",
    "aws_cognito_identity_pool_id": "us-east-2:a38f1254-41ec-4542-9921-252f1a9cc369",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_isSPZF8Af",
    "aws_user_pools_web_client_id": "9ra47orsjr6g4ot0id0p2ubd1",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "productstorage10256-main",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
